[package]
name = "tauri-app"
version = "0.2.0"
description = "A Tauri App"
authors = ["Alex Spinu"]
edition = "2024"
default-run = "tauri-app"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.6", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.7.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
hyprland = { version = "0.4.0-beta.3", features = ["default", "hyprpaper", "dispatch", "ctl", "config", "data", "keyword", "listener", "tokio", "async-lite", "ahash"] }
tokio = { version = "1.53.1", features = ["time"] }
hyprlang = { version = "0.5.0", features = ["hyprland", "mutation"] }
toml_edit = "0.25"
glob = "0.3.4"
