// Dispatcher descriptions mapping
export const DISPATCHER_DESCRIPTIONS: Record<string, string> = {
  exec: "Execute a shell command",
  killactive: "Close the active window",
  togglefloating: "Toggle floating mode for the active window",
  fullscreen: "Toggle fullscreen mode",
  workspace: "Switch to a specific workspace",
  movetoworkspacesilent: "Move window to workspace without switching to it",
  togglegroup: "Toggle the current window's group",
  changegroupactive: "Change the active window in a group",
  togglesplit: "Toggle split direction",
  swapsplit: "Swap split direction",
  splitratio: "Change split ratio",
  movefocus: "Move focus in a direction (l/r/u/d)",
  movewindow: "Move window in a direction",
  resizeactive: "Resize the active window",
  centerwindow: "Center the active window",
  cyclenext: "Cycle to the next window",
  swapnext: "Swap with the next window",
  focusmonitor: "Focus a specific monitor",
  movecursortocorner: "Move cursor to a corner",
  movecursor: "Move cursor to coordinates",
  exit: "Exit Hyprland",
  forcerendererreload: "Force renderer reload",
  movecurrentworkspacetomonitor: "Move current workspace to a monitor",
  focusworkspaceoncurrentmonitor: "Focus workspace on current monitor",
  focusurgentorlast: "Focus urgent or last window",
  togglespecialworkspace: "Toggle special workspace (scratchpad)",
  movetoworkspace: "Move window to workspace",
  pin: "Pin the active window",
  mouse: "Mouse button action",
  bringactivetotop: "Bring active window to top",
  alterzorder: "Change window z-order (top/bottom)",
  lockgroups: "Lock/unlock window groups",
  lockactivegroup: "Lock/unlock the active group",
  moveintogroup: "Move window into a group",
  moveoutofgroup: "Move window out of group",
  movegroupwindow: "Move window within group",
  global: "Global shortcut (works when not focused)",
  pass: "Pass key to active window",
  sendshortcut: "Send shortcut to a window",
  dpms: "Control monitor power (on/off)",
  pseudo: "Toggle pseudo-tiling mode",
  layoutmsg: "Send message to layout",
  toggleopaque: "Toggle window opacity",
  submap: "Switch to a key submap",
};

// All available dispatchers
export const AVAILABLE_DISPATCHERS = [
  "exec",
  "killactive",
  "togglefloating",
  "fullscreen",
  "workspace",
  "movetoworkspace",
  "movetoworkspacesilent",
  "togglegroup",
  "changegroupactive",
  "togglesplit",
  "swapsplit",
  "splitratio",
  "movefocus",
  "movewindow",
  "resizeactive",
  "centerwindow",
  "cyclenext",
  "swapnext",
  "focusmonitor",
  "movecursortocorner",
  "movecursor",
  "exit",
  "forcerendererreload",
  "movecurrentworkspacetomonitor",
  "focusworkspaceoncurrentmonitor",
  "focusurgentorlast",
  "togglespecialworkspace",
  "movetoworkspace",
  "pin",
  "mouse",
  "bringactivetotop",
  "alterzorder",
  "lockgroups",
  "lockactivegroup",
  "moveintogroup",
  "moveoutofgroup",
  "movegroupwindow",
  "global",
  "pass",
  "sendshortcut",
  "dpms",
  "pseudo",
  "layoutmsg",
  "toggleopaque",
  "submap",
];

// Available modifier keys
export const MODIFIER_OPTIONS = ["SUPER", "SHIFT", "ALT", "CTRL"] as const;

export type ModifierKey = (typeof MODIFIER_OPTIONS)[number];
