// Dispatcher descriptions mapping. Names are the classic dispatcher names; for Lua
// configs the backend translates them to the matching hl.dsp.* call.
export const DISPATCHER_DESCRIPTIONS: Record<string, string> = {
  exec: "Execute a shell command",
  execr: "Execute a raw shell command (no window rules)",
  killactive: "Close the active window",
  forcekillactive: "Kill the active window's process",
  closewindow: "Close a window (window selector)",
  killwindow: "Kill a window's process (window selector)",
  signal: "Send a signal to the active window",
  signalwindow: "Send a signal to a window (window,signal)",
  togglefloating: "Toggle floating mode for the active window",
  setfloating: "Make the active window floating",
  settiled: "Make the active window tiled",
  fullscreen: "Toggle fullscreen (0 fullscreen, 1 maximize; optional set/unset)",
  fullscreenstate: "Set internal and client fullscreen state (internal client)",
  pseudo: "Toggle pseudo-tiling mode",
  pin: "Pin the active window",
  centerwindow: "Center the active window",
  workspace: "Switch to a specific workspace",
  focusworkspaceoncurrentmonitor: "Focus workspace on current monitor",
  renameworkspace: "Rename a workspace (id name)",
  movetoworkspace: "Move window to workspace",
  movetoworkspacesilent: "Move window to workspace without switching to it",
  togglespecialworkspace: "Toggle special workspace (scratchpad)",
  movefocus: "Move focus in a direction (l/r/u/d)",
  movewindow: "Move window in a direction, or to a monitor (mon:NAME)",
  movewindoworgroup: "Move window in a direction, entering or leaving groups",
  swapwindow: "Swap with the window in a direction or matching a selector",
  swapnext: "Swap with the next window (prev for previous)",
  cyclenext: "Cycle to the next window (prev, tiled, floating)",
  focuswindow: "Focus a window (window selector)",
  focusmonitor: "Focus a specific monitor",
  focusurgentorlast: "Focus urgent or last window",
  focuscurrentorlast: "Focus the previously focused window",
  resizeactive: "Resize the active window (x y, or exact x y)",
  moveactive: "Move the active window (x y, or exact x y)",
  resizewindowpixel: "Resize a window (x y,window)",
  movewindowpixel: "Move a window (x y,window)",
  tagwindow: "Toggle a tag on a window (tag [window])",
  toggleswallow: "Toggle window swallowing",
  bringactivetotop: "Bring active window to top",
  alterzorder: "Change window z-order (top/bottom[,window])",
  setprop: "Set a window property (window property value)",
  mouse: "Drag or resize with the mouse (movewindow/resizewindow)",
  togglegroup: "Toggle the current window's group",
  changegroupactive: "Change the active window in a group (f, b or index)",
  movegroupwindow: "Move window within group (b for backwards)",
  lockgroups: "Lock/unlock window groups",
  lockactivegroup: "Lock/unlock the active group",
  moveintogroup: "Move window into a group",
  moveintoorcreategroup: "Move window into a group, creating one if needed",
  moveoutofgroup: "Move window out of group",
  denywindowfromgroup: "Prevent the active window from joining groups (on/off/toggle)",
  movecursortocorner: "Move cursor to a corner",
  movecursor: "Move cursor to coordinates",
  movecurrentworkspacetomonitor: "Move current workspace to a monitor",
  moveworkspacetomonitor: "Move a workspace to a monitor (workspace monitor)",
  swapactiveworkspaces: "Swap active workspaces of two monitors",
  submap: "Switch to a key submap",
  pass: "Pass key to a window",
  sendshortcut: "Send shortcut to a window (MODS, key[, window])",
  sendkeystate: "Send a key state to a window (MODS, key, down|up|repeat[, window])",
  layoutmsg: "Send message to layout (e.g. togglesplit)",
  dpms: "Control monitor power (on/off/toggle [monitor])",
  exit: "Exit Hyprland",
  forcerendererreload: "Force renderer reload",
  forceidle: "Pretend the session has been idle for N seconds",
  releaseinputcapture: "Release an active input capture",
  event: "Emit a custom event on the event socket",
  global: "Global shortcut (works when not focused)",
  lua: "Raw Lua dispatcher, e.g. hl.dsp.window.close() or function() ... end",
};

// All available dispatchers (shared by hyprland.conf and hyprland.lua)
export const AVAILABLE_DISPATCHERS = [
  "exec",
  "execr",
  "killactive",
  "forcekillactive",
  "closewindow",
  "killwindow",
  "signal",
  "signalwindow",
  "togglefloating",
  "setfloating",
  "settiled",
  "fullscreen",
  "fullscreenstate",
  "pseudo",
  "pin",
  "centerwindow",
  "workspace",
  "focusworkspaceoncurrentmonitor",
  "renameworkspace",
  "movetoworkspace",
  "movetoworkspacesilent",
  "togglespecialworkspace",
  "movefocus",
  "movewindow",
  "movewindoworgroup",
  "swapwindow",
  "swapnext",
  "cyclenext",
  "focuswindow",
  "focusmonitor",
  "focusurgentorlast",
  "focuscurrentorlast",
  "resizeactive",
  "moveactive",
  "resizewindowpixel",
  "movewindowpixel",
  "tagwindow",
  "toggleswallow",
  "bringactivetotop",
  "alterzorder",
  "setprop",
  "mouse",
  "togglegroup",
  "changegroupactive",
  "movegroupwindow",
  "lockgroups",
  "lockactivegroup",
  "moveintogroup",
  "moveintoorcreategroup",
  "moveoutofgroup",
  "denywindowfromgroup",
  "movecursortocorner",
  "movecursor",
  "movecurrentworkspacetomonitor",
  "moveworkspacetomonitor",
  "swapactiveworkspaces",
  "submap",
  "pass",
  "sendshortcut",
  "sendkeystate",
  "layoutmsg",
  "dpms",
  "exit",
  "forcerendererreload",
  "forceidle",
  "releaseinputcapture",
  "event",
  "global",
];

// Only meaningful for hyprland.lua configs
export const LUA_ONLY_DISPATCHERS = ["lua"];

// Available modifier keys
export const MODIFIER_OPTIONS = ["SUPER", "SHIFT", "ALT", "CTRL"] as const;

export type ModifierKey = (typeof MODIFIER_OPTIONS)[number];
